# Create and Access SQLite Database Using Python

## Objective
In this lab, I will:
- Create a SQLite database using Python
- Create a table called INSTRUCTOR
- Insert data into the table
- Query and update the data
- Load the data into pandas

## Step 1: Import Required Library

We begin by importing the sqlite3 library, which allows Python to interact with SQLite databases.

In [1]:
import sqlite3

## Step 2: Create a Database Connection

Here we create a connection to a database called INSTRUCTOR.db.

If the database does not exist, SQLite will automatically create it.

In [2]:
conn = sqlite3.connect("INSTRUCTOR.db")

## Step 3: Create a Cursor Object

The cursor is used to execute SQL commands such as creating tables and inserting data.

In [3]:
cursor_obj = conn.cursor()

## Step 4: Create the INSTRUCTOR Table

We now create a table called INSTRUCTOR with the following columns:
- ID (Primary Key)
- First Name
- Last Name
- City
- Country Code

In [4]:
cursor_obj.execute("""
CREATE TABLE IF NOT EXISTS INSTRUCTOR(
ID INTEGER PRIMARY KEY NOT NULL,
FNAME VARCHAR(20),
LNAME VARCHAR(20),
CITY VARCHAR(20),
CCODE CHAR(2)
)
""")

print("Table created successfully")

Table created successfully

## Step 5: Insert Data into the Table

We will insert sample records into the INSTRUCTOR table.

In [5]:
cursor_obj.execute("INSERT INTO INSTRUCTOR VALUES (1, 'Rav', 'Ahuja', 'TORONTO', 'CA')")
cursor_obj.execute("INSERT INTO INSTRUCTOR VALUES (2, 'Raul', 'Chong', 'Markham', 'CA')")
cursor_obj.execute("INSERT INTO INSTRUCTOR VALUES (3, 'Hima', 'Vasudevan', 'Chicago', 'US')")

conn.commit()

print("Data inserted successfully")

Data inserted successfully

We use commit() to save the changes permanently to the database.
## Step 6: Query Data from the Table

We use a SELECT statement to retrieve all records from the INSTRUCTOR table.

In [6]:
cursor_obj.execute("SELECT * FROM INSTRUCTOR")

rows = cursor_obj.fetchall()

print("All data:")
for row in rows:
    print(row)

All data:
(1, 'Rav', 'Ahuja', 'TORONTO', 'CA')
(2, 'Raul', 'Chong', 'Markham', 'CA')
(3, 'Hima', 'Vasudevan', 'Chicago', 'US')

## Step 7: Fetch One Record

We can also retrieve a limited number of rows using fetchmany().

In [7]:
cursor_obj.execute("SELECT * FROM INSTRUCTOR")

one_row = cursor_obj.fetchmany(1)

print("First row:")
print(one_row)

First row:
[(1, 'Rav', 'Ahuja', 'TORONTO', 'CA')]

## Step 8: Update Data in the Table

We update the city of Rav from TORONTO to MOOSETOWN.

In [8]:
cursor_obj.execute(
    "UPDATE INSTRUCTOR SET CITY='MOOSETOWN' WHERE FNAME='Rav'"
)

conn.commit()

## Verify Update

In [9]:
cursor_obj.execute("SELECT * FROM INSTRUCTOR")

rows = cursor_obj.fetchall()

for row in rows:
    print(row)

(1, 'Rav', 'Ahuja', 'MOOSETOWN', 'CA')
(2, 'Raul', 'Chong', 'Markham', 'CA')
(3, 'Hima', 'Vasudevan', 'Chicago', 'US')

## Step 9: Load Data into Pandas

We use pandas to convert the SQL table into a DataFrame for analysis.

In [10]:
import pandas as pd

df = pd.read_sql_query("SELECT * FROM INSTRUCTOR", conn)

df

   ID FNAME      LNAME       CITY CCODE
0   1   Rav      Ahuja  MOOSETOWN    CA
1   2  Raul      Chong    Markham    CA
2   3  Hima  Vasudevan    Chicago    US

## Data Analysis

We can perform operations such as sorting and checking the shape of the data.

In [11]:
df.sort_values(by="LNAME", ascending=False)

   ID FNAME      LNAME       CITY CCODE
2   3  Hima  Vasudevan    Chicago    US
1   2  Raul      Chong    Markham    CA
0   1   Rav      Ahuja  MOOSETOWN    CA

In [12]:
df.shape

(3, 5)